/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PbtDashboard extends javax.swing.JFrame {

    
    ParabitDBC dbc;
    PbtEmpData empdata;
    /**
     * Creates new form PbtDashboard
     */
    public PbtDashboard(PbtEmpData data) {
        empdata = data;
        initComponents();
        DefaultTableModel model = (DefaultTableModel)nottable.getModel();
        String query = "SELECT * FROM pbtnotification";
        dbc = new ParabitDBC();
        model.setRowCount(0);
        try {
            dbc.rs1=dbc.stm.executeQuery(query);
            while(dbc.rs1.next())
            {
                String senderid = dbc.rs1.getString("SenderCeid");
                String message = dbc.rs1.getString("Message");
                String time = dbc.rs1.getString("Time");
                Object row[] = {senderid, message, time};
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PbtDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnme = new javax.swing.JButton();
        btnnotify = new javax.swing.JButton();
        btnes = new javax.swing.JButton();
        btncs = new javax.swing.JButton();
        btnwa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nottable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnme.setText("Manage Employee");
        btnme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmeActionPerformed(evt);
            }
        });

        btnnotify.setText("Notification");

        btnes.setText("Employee Summary");

        btncs.setText("Census Summary");

        btnwa.setText("Work Assingment");

        nottable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender ID", "Message", "Time"
            }
        ));
        jScrollPane1.setViewportView(nottable);

        jLabel1.setText("CAA Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnes)
                        .addGap(47, 47, 47)
                        .addComponent(btncs, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnme)
                                .addGap(46, 46, 46)
                                .addComponent(btnwa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnnotify, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnotify, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnme, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmeActionPerformed
        PbtManageEmployee pme = new PbtManageEmployee(empdata);
        pme.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncs;
    private javax.swing.JButton btnes;
    private javax.swing.JButton btnme;
    private javax.swing.JButton btnnotify;
    private javax.swing.JButton btnwa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nottable;
    // End of variables declaration//GEN-END:variables
}
