/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class PbtPosts extends javax.swing.JFrame {

    /**
     * Creates new form PbtPosts
     */
    PbtEmpData empdata;
    
    public PbtPosts(PbtEmpData data) {
        initComponents();
        empdata = data;
        //ParabitDBC dbc = new ParabitDBC();
        System.out.println(data);
        switch (data.getEmpgrade()) {
            case 100:
                btnministry.setEnabled(false);
                btncensusdept.setEnabled(false);
                break;
            case 200:
                btnpmo.setEnabled(false);
                btncensusdept.setEnabled(false);
                break;
            default:
                btnpmo.setEnabled(false);
                btnministry.setEnabled(false);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpmo = new javax.swing.JButton();
        btnministry = new javax.swing.JButton();
        btncensusdept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnpmo.setText("PMO");
        btnpmo.setMaximumSize(new java.awt.Dimension(145, 25));
        btnpmo.setMinimumSize(new java.awt.Dimension(145, 25));
        btnpmo.setPreferredSize(new java.awt.Dimension(145, 25));
        btnpmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpmoActionPerformed(evt);
            }
        });

        btnministry.setText("Ministry");
        btnministry.setMaximumSize(new java.awt.Dimension(145, 25));
        btnministry.setMinimumSize(new java.awt.Dimension(145, 25));
        btnministry.setPreferredSize(new java.awt.Dimension(145, 25));
        btnministry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnministryActionPerformed(evt);
            }
        });

        btncensusdept.setText("Census Department");
        btncensusdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncensusdeptActionPerformed(evt);
            }
        });

        jLabel1.setText("Post");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnpmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnministry, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncensusdept))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpmo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnministry, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncensusdept, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnministryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnministryActionPerformed

        PbtCensusDept pcd = new PbtCensusDept(empdata);
        pcd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnministryActionPerformed

    private void btnpmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpmoActionPerformed

        PbtCensusDept pcd = new PbtCensusDept(empdata);
        pcd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpmoActionPerformed

    private void btncensusdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncensusdeptActionPerformed

        PbtCensusDept pcd = new PbtCensusDept(empdata);
        pcd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btncensusdeptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtPosts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtPosts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtPosts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtPosts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PbtPosts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncensusdept;
    private javax.swing.JButton btnministry;
    private javax.swing.JButton btnpmo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
